export const labelRows = `
Language|Sprache|Langue|Lingua|Idioma|Język|Limbă|Taal|Idioma|Γλώσσα|Jazyk|Nyelv|Språk
Biography|Biografie|Biographie|Biografia|Biografía|Biografia|Biografie|Biografie|Biografia|Βιογραφία|Životopis|Életrajz|Biografi
Primary|Hauptnavigation|Navigation principale|Navigazione principale|Navegación principal|Nawigacja główna|Navigare principală|Hoofdnavigatie|Navegação principal|Κύρια πλοήγηση|Hlavní navigace|Fő navigáció|Huvudnavigering
Social media links|Social-Media-Links|Liens réseaux sociaux|Link social|Enlaces de redes sociales|Linki społecznościowe|Linkuri sociale|Socialmedialinks|Ligações sociais|Σύνδεσμοι κοινωνικών μέσων|Sociální odkazy|Közösségi linkek|Länkar till sociala medier
More social media links|Weitere Social-Media-Links|Autres liens sociaux|Altri link social|Más enlaces sociales|Więcej linków społecznościowych|Alte linkuri sociale|Meer socialmedialinks|Mais ligações sociais|Περισσότεροι κοινωνικοί σύνδεσμοι|Další sociální odkazy|További közösségi linkek|Fler sociala länkar
Official social links|Offizielle Social-Links|Liens sociaux officiels|Link social ufficiali|Enlaces sociales oficiales|Oficjalne linki społecznościowe|Linkuri sociale oficiale|Officiële socialmedialinks|Ligações sociais oficiais|Επίσημοι κοινωνικοί σύνδεσμοι|Oficiální sociální odkazy|Hivatalos közösségi linkek|Officiella sociala länkar
Services and platforms|Leistungen und Plattformen|Services et plateformes|Servizi e piattaforme|Servicios y plataformas|Usługi i platformy|Servicii și platforme|Diensten en platforms|Serviços e plataformas|Υπηρεσίες και πλατφόρμες|Služby a platformy|Szolgáltatások és platformok|Tjänster och plattformar
Where to see the work|Wo Sie die Arbeiten finden|Où voir les créations|Dove vedere i lavori|Dónde ver el trabajo|Gdzie zobaczyć prace|Unde vezi lucrările|Waar u het werk ziet|Onde ver o trabalho|Πού θα δείτε τα έργα|Kde vidět práce|Hol láthatók a munkák|Var arbetet finns
Direct contact alternatives|Direkte Kontaktalternativen|Autres contacts directs|Alternative di contatto diretto|Alternativas de contacto directo|Alternatywy kontaktu bezpośredniego|Alternative de contact direct|Alternatieven voor direct contact|Alternativas de contacto direto|Εναλλακτική άμεση επικοινωνία|Alternativy přímého kontaktu|Közvetlen kapcsolati lehetőségek|Alternativ för direktkontakt
Light and dark theme|Helles und dunkles Design|Thème clair et sombre|Tema chiaro e scuro|Tema claro y oscuro|Jasny i ciemny motyw|Temă luminoasă și întunecată|Licht en donker thema|Tema claro e escuro|Φωτεινό και σκοτεινό θέμα|Světlý a tmavý vzhled|Világos és sötét téma|Ljust och mörkt tema
Dark Light color theme: switch to dark mode|Helles und dunkles Design: zum dunklen Modus wechseln|Thème clair/sombre : passer au mode sombre|Tema chiaro/scuro: passa a scuro|Tema claro/oscuro: cambiar a oscuro|Motyw jasny/ciemny: przełącz na ciemny|Temă luminoasă/întunecată: schimbă pe întunecat|Licht/donker thema: schakel naar donker|Tema claro/escuro: mudar para escuro|Φωτεινό/σκοτεινό θέμα: αλλαγή σε σκοτεινό|Světlý/tmavý vzhled: přepnout na tmavý|Világos/sötét téma: váltás sötétre|Ljust/mörkt tema: växla till mörkt
Dark Light color theme: switch to light mode|Helles und dunkles Design: zum hellen Modus wechseln|Thème clair/sombre : passer au mode clair|Tema chiaro/scuro: passa a chiaro|Tema claro/oscuro: cambiar a claro|Motyw jasny/ciemny: przełącz na jasny|Temă luminoasă/întunecată: schimbă pe luminos|Licht/donker thema: schakel naar licht|Tema claro/escuro: mudar para claro|Φωτεινό/σκοτεινό θέμα: αλλαγή σε φωτεινό|Světlý/tmavý vzhled: přepnout na světlý|Világos/sötét téma: váltás világosra|Ljust/mörkt tema: växla till ljust
Loading portfolio|Portfolio wird geladen|Chargement du portfolio|Caricamento portfolio|Cargando portafolio|Ładowanie portfolio|Se încarcă portofoliul|Portfolio laden|A carregar portefólio|Φόρτωση χαρτοφυλακίου|Načítání portfolia|Portfólió betöltése|Laddar portfolio
Describe the idea, the intended audience, and what you want the finished result to accomplish.|Beschreiben Sie die Idee, Zielgruppe und das gewünschte Ziel des fertigen Ergebnisses.|Décrivez l’idée, le public et l’objectif du résultat final.|Descrivi idea, pubblico e obiettivo del risultato finale.|Describe idea, audiencia y objetivo del resultado final.|Opisz pomysł, odbiorców i cel gotowego rezultatu.|Descrie ideea, publicul și obiectivul rezultatului final.|Beschrijf het idee, de doelgroep en het doel van het eindresultaat.|Descreva ideia, público e objetivo do resultado final.|Περιγράψτε την ιδέα, το κοινό και τον στόχο του τελικού αποτελέσματος.|Popište nápad, publikum a cíl hotového výsledku.|Írja le az ötletet, célközönséget és a végső eredmény célját.|Beskriv idén, målgruppen och målet med slutresultatet.
Your language preference is saved only in your browser as|Ihre Sprachwahl wird nur in Ihrem Browser gespeichert als|Votre choix de langue est conservé uniquement dans votre navigateur sous|La lingua scelta è salvata solo nel browser come|Tu preferencia de idioma se guarda solo en tu navegador como|Wybór języka zapisuje się tylko w przeglądarce jako|Preferința de limbă se salvează doar în browser ca|Uw taalkeuze wordt alleen in uw browser opgeslagen als|A preferência de idioma é guardada apenas no navegador como|Η επιλογή γλώσσας αποθηκεύεται μόνο στον browser ως|Volba jazyka se ukládá pouze v prohlížeči jako|Nyelvi választása csak a böngészőben tárolódik mint|Språkvalet sparas bara i webbläsaren som
. Translations are local files. No translation service receives your text or browsing data. Clear this website's browser data to remove the saved preference.|. Übersetzungen sind lokale Dateien. Kein Übersetzungsdienst erhält Ihre Texte oder Browserdaten. Löschen Sie die Websitedaten, um die Wahl zu entfernen.|. Les traductions sont locales. Aucun service ne reçoit vos textes ou données de navigation. Effacez les données du site pour supprimer ce choix.|. Le traduzioni sono file locali. Nessun servizio riceve testi o dati di navigazione. Cancella i dati del sito per rimuovere la preferenza.|. Las traducciones son locales. Ningún servicio recibe textos ni datos de navegación. Borra los datos del sitio para eliminar la preferencia.|. Tłumaczenia są lokalne. Żadna usługa nie otrzymuje tekstów ani danych przeglądania. Usuń dane strony, aby skasować wybór.|. Traducerile sunt fișiere locale. Niciun serviciu nu primește texte sau date de navigare. Șterge datele site-ului pentru a elimina preferința.|. Vertalingen zijn lokale bestanden. Geen dienst ontvangt tekst of browsegegevens. Wis sitegegevens om de keuze te verwijderen.|. As traduções são locais. Nenhum serviço recebe textos ou dados de navegação. Apague dados do site para remover a preferência.|. Οι μεταφράσεις είναι τοπικά αρχεία. Καμία υπηρεσία δεν λαμβάνει κείμενα ή δεδομένα περιήγησης. Διαγράψτε δεδομένα ιστοτόπου για αφαίρεση της επιλογής.|. Překlady jsou místní soubory. Žádná služba nedostává text ani údaje prohlížení. Vymažte data webu pro odstranění volby.|. A fordítások helyi fájlok. Semmilyen szolgáltatás nem kap szöveget vagy böngészési adatokat. A webhelyadatok törlésével eltávolíthatja a választást.|. Översättningar är lokala filer. Ingen tjänst får text eller surfdata. Radera webbplatsdata för att ta bort valet.
`.trim().split('\n').map(line => line.split('|'));
labelRows.push(['Loading Portfolio', ...labelRows.find(row => row[0] === 'Loading portfolio').slice(1)]);
const date = new Date('2026-09-25T12:00:00Z');
const updated = ['Last updated:','Zuletzt aktualisiert:','Dernière mise à jour :','Ultimo aggiornamento:','Última actualización:','Ostatnia aktualizacja:','Ultima actualizare:','Laatst bijgewerkt:','Última atualização:','Τελευταία ενημέρωση:','Poslední aktualizace:','Utolsó frissítés:','Senast uppdaterad:'];
const locales = ['en-GB','de','fr','it','es','pl','ro','nl','pt','el','cs','hu','sv'];
labelRows.push(locales.map((locale, index) => updated[index] + ' ' + new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(date)));
// The German legal-document names are deliberately retained as identifiers.
for (const name of ['Impressum ·','Datenschutzerklärung ·']) labelRows.push(Array(13).fill(name));
